const gridTypes = {
  demoGrid: 'demoGrid',
  tankVolumeHistoryGrid: 'tankVolumeHistoryGrid',
  fuelGradeSetup: 'fuelGradeSetup',
  fuelGradeTankDetailsGrid: 'fuelGradeTankDetailsGrid',
  fuelGradeBlendGrid: 'fuelGradeBlendGrid',
  itemGroupGrid: 'itemGroupGrid',
  vendorItemGrid: 'vendorItemGrid',
  userRoleWiseStoreGrid: 'userRoleWiseStoreGrid',
  storeItemsGrid: 'storeItemsGrid',
  editItemVendorGrid: 'editItemVendorGrid',
  editItemGroupGrid: 'editItemGroupGrid',
  multiplierItemGrid: 'multiplierItemGrid',
  linkedItemGrid: 'linkedItemGrid',
  customerPriceGroupGrid: 'customerPriceGroupGrid',
  itemCustomPriceGroupGrid: 'itemCustomPriceGroupGrid',
  fuelGradeBlendDetailsGrid: 'fuelGradeBlendDetailsGrid',
  fuelInventoryGrid:'fuelInventoryGrid',
  fuelGradeGrid: 'fuelGradeGrid',
  invoiceChargesGrid: 'invoiceChargesGrid',
  invoiceChargesGridNonEditable: 'invoiceChargesGridNonEditable',
  invoicePaymentGrid: 'invoicePaymentGrid',
  invoicePaymentGridNonEditable: 'invoicePaymentGridNonEditable',
  fuelInvoiceOtherChargesGrid: 'fuelInvoiceOtherChargesGrid',
  tankVolumeDetailGrid: 'tankVolumeDetailGrid',
  editCompetitorPricingGrid: 'editCompetitorPricingGrid',
  fuelPricingGrid: 'fuelPricingGrid',
  priceGItemGrid: 'priceGItemGrid',
  storeItemsGridEditable: 'storeItemsGridEditable',
  multipacksIGrid: 'multipacksIGrid',
  edittableBOLGrid: 'edittableBOLGrid',
  edittableBOLResponseGrid: 'edittableBOLResponseGrid',
  departmentUpdateSellingPriceGrid: 'departmentUpdateSellingPriceGrid',
  departmentProductNameForEDIGrid: 'departmentProductNameForEDIGrid',
  fuelReconciliationOtherChargesGrid: 'fuelReconciliationOtherChargesGrid',
  companyReconParameterGrid: 'companyReconParameterGrid',
  addInvoicesDetailsGrid: 'addInvoicesDetailsGrid',
  salesTaxGrid: 'salesTaxGrid',
  salesRestrictionGrid: 'salesRestrictionGrid',
  storeFeesGrid: 'storeFeesGrid',
  paymentMethodGrid: 'paymentMethodGrid',
  privilageGrid: 'privilageGrid',
  houseAccountGrid: 'houseAccountGrid',
  masterlinkedItemGrid: 'masterlinkedItemGrid',
  lotteryInventoryGrid: 'lotteryInventoryGrid',
  dayReconMOPGrid: 'dayReconMOPGrid',
  bankDepositGrid: ' bankDepositGrid',
  userPrivilegeGrid: 'userPrivilegeGrid',
  addInvoicesDetailsGridNonEditable: 'addInvoicesDetailsGridNonEditable',
  lotteryGameGrid: 'lotteryGameGrid',
  atmGrid: 'atmGrid',
  bankGrid: 'bankGrid'
};
const defaultSetting = {
  DEFAULT: {
    rowSelection: 'single',
    singleClickEdit: true,
  },
  itemGroupGrid: {
    rowSelection: 'multiple',
    suppressRowClickSelection: true
  },
  editItemVendorGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 35,
  },
  editItemGroupGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true
  },
  tankVolumeHistoryGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    headerHeight: 48
  },
  storeItemsGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    //  suppressRowClickSelection: true,
    headerHeight: 41,
    isSearchTextBoxRequired: false
  },
  storeItemsGridEditable: {
    rowSelection: 'single',
    singleClickEdit: false,
    // suppressRowClickSelection: true,
    headerHeight: 41,
    isSearchTextBoxRequired: false
  },
  itemCustomPriceGroupGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
  },
  fuelGradeBlendDetailsGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
  },
  fuelGradeGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false
  },
  invoiceChargesGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 40,
  },
  invoicePaymentGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 40,
  },
  fuelInvoiceOtherChargesGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 41
  },
  tankVolumeDetailGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: true,
    headerHeight: 41
  },
  editCompetitorPricingGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: true,
    headerHeight: 41
  },
  fuelPricingGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: true
  },
  priceGItemGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 35,
  },
  fuelInventoryGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 35,
  },
  multiplierItemGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false
    , headerHeight: 35,
  },
  linkedItemGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 35,
  },
  multipacksIGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 35,
  },
  edittableBOLGrid: {
    rowSelection: 'multiple',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 35,
  },
  edittableBOLResponseGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 35,
  },
  departmentUpdateSellingPriceGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 41,

  }, departmentProductNameForEDIGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 41,
  },
  fuelReconciliationOtherChargesGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 35
  },
  companyReconParameterGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false
  },
  addInvoicesDetailsGrid: {
    rowSelection: 'multiple',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 50,
  },
  salesTaxGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 41,
  },
  salesRestrictionGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 41,
  },
  storeFeesGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 41,
  },
  paymentMethodGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 41,
  },
  vendorItemGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 35,
  },
  privilageGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 35,
  },
  houseAccountGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 50,
  },
  masterlinkedItemGrid: {
    rowSelection: 'single',
    singleClickEdit: false,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 50,
  },
  lotteryInventoryGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 55,
  },
  dayReconMOPGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 40,
  },
  atmGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 40,
  },
  bankGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 40,
  },
  bankDepositGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 40,
  },
  userPrivilegeGrid: {
    rowSelection: 'single',
    singleClickEdit: true,
    suppressRowClickSelection: true,
    isSearchTextBoxRequired: false,
    headerHeight: 40,
  },
};

export const editGridOptions = {
  gridTypes: gridTypes,
  defaultSetting: defaultSetting
};
