const gridTypes = {
    demoGrid: 'demoGrid',
    companyUserMgmtGrid: 'companyUserMgmtGrid',
    companyReconParameterGrid: 'companyReconParameterGrid',
    fuelGradeGrid: 'fuelGradeGrid',
    companyGrid: 'companyGrid',
    paymentSourceGrid: 'paymentSourceGrid',
    employeeTimeCardGrid: 'employeeTimeCardGrid',
    siteMessageGrid: 'siteMessageGrid',
    itemRefenceGrid: 'itemRefenceGrid',
    sellingPriceGrid: 'sellingPriceGrid',
    storeInfoGrid: 'storeInfoGrid',
    demoExpandableGrid: 'demoExpandableGrid',
    storeCompetitorGrid: 'storeCompetitorGrid',
    salesRestrictionGrid: 'salesRestrictionGrid',
    departmentGrid: 'departmentGrid',
    departmentLocationGrid: 'departmentLocationGrid',
    departmentHistoryGrid: 'departmentHistoryGrid',
    deptWithoutLocGrid: 'deptWithoutLocGrid',
    fuelGradeMappingGrid: 'fuelGradeMappingGrid',
    fuelGradeTankDetailsGrid: 'fuelGradeTankDetailsGrid',
    fuelInventoryActivityGrid: 'fuelInventoryActivityGrid',
    storeFuelGradeTaxesGrid: 'storeFuelGradeTaxesGrid',
    salesTaxGrid: 'salesTaxGrid',
    paymentMethodGrid: 'paymentMethodGrid',
    invoicesDetailsGrid: 'invoicesDetailsGrid',
    vendorGrid: 'vendorGrid',
    lotteryInventoryGrid: 'lotteryInventoryGrid',
    lotteryGameGrid: 'lotteryGameGrid',
    storeFeesGrid: 'storeFeesGrid',
    comfirmPackGrid: 'comfirmPackGrid',
    activatePackGrid: 'activatePackGrid',
    masterDepartmentGrid: 'masterDepartmentGrid',
    masterBrandGrid: 'masterBrandGrid',
    masterDepartmentTypeGrid: 'masterDepartmentTypeGrid',
    houseAccountGrid: 'houseAccountGrid',
    priceGroupGrid: 'priceGroupGrid',
    activateConfirmGrid: 'activateConfirmGrid',
    mixMatchesGroupGrid: 'mixMatchesGroupGrid',
    vendorItemGrid: 'vendorItemGrid',
    itemDetailGrid: 'itemDetailGrid',
    manageItemsByPriceGrpGrid: 'manageItemsByPriceGrpGrid',
    manageItemsByPriceGrpGridSingleStore: 'manageItemsByPriceGrpGridSingleStore',
    manageItemsGrid: 'manageItemsGrid',
    manageItemsPricingGrid: 'manageItemsPricingGrid',
    manageItemsPricingGridWithoutStore: 'manageItemsPricingGridWithoutStore',
    itemByPriceGroupGrid: 'itemByPriceGroupGrid',
    advmultipacksIGrid: 'advmultipacksIGrid',
    linkedItemsGrid: 'linkedItemsGrid',
    multiplierItemGrid: 'multiplierItemGrid',
    priceGroupItemGrid: 'priceGroupItemGrid',
    storeItemsGrid: 'storeItemsGrid',
    editItemVendorGrid: 'editItemVendorGrid',
    storeItemsGridCase: 'storeItemsGridCase',
    mixMatchItemGrid: 'mixMatchItemGrid',
    mixMatchPriceLocationGrid: 'mixMatchPriceLocationGrid',
    mixMatchStoreGrid: 'mixMatchStoreGrid',
    deletePOSItemGrid: 'deletePOSItemGrid',
    itemMaintanenceGrid: 'itemMaintanenceGrid',
    includedItemListMaintanenceGrid: 'includedItemListMaintanenceGrid',
    itemListMaintanenceGrid: 'itemListMaintanenceGrid',
    physicalInventoryGrid: 'physicalInventoryGrid',
    multipacksIGrid: 'multipacksIGrid',
    stockTransactionsGrid: 'stockTransactionsGrid',
    masterInventoryBuyTagGrid: 'masterInventoryBuyTagGrid',
    supreItemsGrid: 'supreItemsGrid',
    cBuyDownScheduleGrid: 'cBuyDownScheduleGrid',
    addBuyDownScheduleGrid: 'addBuyDownScheduleGrid',
    currentPriceScheduleGrid: 'currentPriceScheduleGrid',
    newPriceScheduleGrid: 'newPriceScheduleGrid',
    masterPriceGroupGrid: 'masterPriceGroupGrid',
    userRoleWiseCompanyGrid: 'userRoleWiseCompanyGrid',
    privilageGrid: 'privilageGrid',
    storeFuelGrid: 'storeFuelGrid',
    fuelGradeTankGrid: 'fuelGradeTankGrid',
    fuelGradeBlendDetailsGrid: 'fuelGradeBlendDetailsGrid',
    fuelTaxGrid: 'fuelTaxGrid',
    fuelInvoiceGrid: 'fuelInvoiceGrid',
    fuelInvoiceDetailGrid: 'fuelInvoiceDetailGrid',
    binInvoiceGrid: 'binInvoiceGrid',
    actionInvoiceGrid: 'actionInvoiceGrid',
    filesInvoiceGrid: 'filesInvoiceGrid',
    orderManagementGrid: 'orderManagementGrid',
    vendorPaymentGrid: 'vendorPaymentGrid',
    reconcileHouseGrid: 'reconcileHouseGrid',
    validateInvoiceGrid: 'validateInvoiceGrid',
    excessInventoryGrid: 'excessInventoryGrid',
    addInvoicesDetailsGrid: 'addInvoicesDetailsGrid',
    invoicesDepartmentDetailsGrid: 'invoicesDepartmentDetailsGrid',
    fuelInvoiceTotalGrid: 'fuelInvoiceTotalGrid',
    pjrSearchGrid: 'pjrSearchGrid',
    itemUPCDetailGrid: 'itemUPCDetailGrid',
    importGroupGrid: 'importGroupGrid',
    itemPriceGroupExpandGrid: 'itemPriceGroupExpandGrid',
    comboMaintanenceGrid: 'comboMaintanenceGrid',
    mixMatchMaintanenceGrid: 'mixMatchMaintanenceGrid',
    companyPriceGroupGrid: 'companyPriceGroupGrid',
    companyPriceGroupNewGrid: 'companyPriceGroupNewGrid',
    tankVolumeHistoryGrid: 'tankVolumeHistoryGrid',
    competitorPricingGrid: 'competitorPricingGrid',
    networkSummaryGrid: 'networkSummaryGrid',
    fuelReconciliationGrid: 'fuelReconciliationGrid',
    fuelReconciliationNetworkBatchGrid: 'fuelReconciliationNetworkBatchGrid',
    fuelReconciliationFuelInvoicechGrid: 'fuelReconciliationFuelInvoicechGrid',
    fuelReconciliationOtherChargesGrid: 'fuelReconciliationOtherChargesGrid',
    scanDataSetupGrid: 'scanDataSetupGrid',
    billofLadingGrid: 'billofLadingGrid',
    taxStrategyGrid: 'taxStrategyGrid',
    salesRestrictCodeGrid: 'salesRestrictCodeGrid',
    tenderCodeGrid: 'tenderCodeGrid',
    mdseCodeGrid: 'mdseCodeGrid',
    passportItemGrid: 'passportItemGrid',
    sapphireCustIDGrid: 'sapphireCustIDGrid',
    sapphireDepartmentGrid: 'sapphireDepartmentGrid',
    sapphireMOPGrid: 'sapphireMOPGrid',
    sapphireTaxGrid: 'sapphireTaxGrid',
    passportHtmlGrid: 'passportHtmlGrid',
    sapphireItemGrid: 'sapphireItemGrid',
    custIDGrid: 'custIDGrid',
    rubyDepartmentGrid: 'rubyDepartmentGrid',
    itemFromCSVGrid: 'itemFromCSVGrid',
    rubyMOPGrid: 'rubyMOPGrid',
    rubyTaxGrid: 'rubyTaxGrid',
    rubySubashGrid: 'rubySubashGrid',
    rubyRGISGrid: 'rubyRGISGrid',
    ediInvoiceGrid: 'ediInvoiceGrid',
    ediProcessGrid: 'ediProcessGrid',
    editfuelReconciliationFuelInvoicechGrid: 'editfuelReconciliationFuelInvoicechGrid',
    editFuelReconciliationNetworkBatchGrid: 'editFuelReconciliationNetworkBatchGrid',
    invoiceDashboardGrid: 'invoiceDashboardGrid',
    MasterPriceBookItemGrid: 'MasterPriceBookItemGrid',
    employeeSetupGrid: 'employeeSetupGrid',
    repCashCheckAmounGrid: 'repCashCheckAmounGrid',
    repDepartmentTypeSalesGrid: 'repDepartmentTypeSalesGrid',
    repGasGradeDatasGrid: 'repGasGradeDatasGrid',
    repMOPDetailsGrid: 'repMOPDetailsGrid',
    dayReconGrid: 'dayReconGrid',
    storeHealthGrid: 'storeHealthGrid',
    serviceHealthGrid: 'serviceHealthGrid',
    pjrGrid: 'pjrGrid',
    dashboardGrid: 'dashboardGrid',
    subscriptionDetailGrid: 'subscriptionDetailGrid',
    storeBillingSubPaymentHistoryGrid: 'storeBillingSubPaymentHistoryGrid',
    storeBillingSubSubscriptionHistoryGrid: 'storeBillingSubSubscriptionHistoryGrid',
    expensesGrid: 'expensesGrid',
    dayReconGasDetailGrid: 'dayReconGasDetailGrid',
    purchasesGrid: 'purchasesGrid',
    importPurchasesGrid: 'importPurchasesGrid',
    importFuelPurchasesGrid: 'importFuelPurchasesGrid',
    dayReconPromotionsDetailGrid: 'dayReconPromotionsDetailGrid',//this grid was used in 3 places
    expensesDetailGrid: 'expensesDetailGrid',
    masterPriceGropDetailGrid: 'masterPriceGropDetailGrid',
    dataFromPOSGrid: 'dataFromPOSGrid',
    dataToPOSGrid: 'dataToPOSGrid',
    comfirmPackBatchGrid: 'comfirmPackBatchGrid',
    activatePackBatchGrid: 'activatePackBatchGrid',
    dashboardSettingGrid: 'dashboardSettingGrid',
    dashboardSettingNonFunGrid: 'dashboardSettingNonFunGrid',
    defaultRolePrivilegeGrid: 'defaultRolePrivilegeGrid',
    userPrivilegeGrid: 'userPrivilegeGrid',
    itemListChildGrpGrid: 'itemListChildGrpGrid',
    salesTotalMgmtGrid: 'salesTotalMgmtGrid',
    companyPriceGroupChildGrid: 'companyPriceGroupChildGrid',
    companyPriceGroupGridChildColWithSPGrid: 'companyPriceGroupGridChildColWithSPGrid',
    priceGrpItemDetailGrid: 'priceGrpItemDetailGrid',
    priceGrpNewItemDetailGrid: 'priceGrpNewItemDetailGrid',
    priceGrpNewItemDetailGrid1: 'priceGrpNewItemDetailGrid1',
    priceGrpNewItemDetailGrid2: 'priceGrpNewItemDetailGrid2',
    storeMixMatchDetailGrid: 'storeMixMatchDetailGrid',
    storeComboDealDetailGrid: 'storeComboDealDetailGrid',
    storeGrpGrid: 'storeGrpGrid',
    itemCatalogGrid: 'itemCatalogGrid',
    itemCatalogStoreGrid: 'itemCatalogStoreGrid',
    itemListChildGrpGridChildGrid: 'itemListChildGrpGridChildGrid',
    itemListOverlayGrpGrid: 'itemListOverlayGrpGrid',
    itemListOverlayGrpGridChildGrid: 'itemListOverlayGrpGridChildGrid',
    scanDataConfig: 'scanDataConfig',
    scanDataAcknowledgment: 'scanDataAcknowledgment',
    ismUpdate: 'ismUpdate',
    buyDownGrid: 'buyDownGrid',
    buyDownStoreDetailsGrid: 'buyDownStoreDetailsGrid',
    priceGroupBuyDownGrid: 'priceGroupBuyDownGrid',
    editBillofLadingGrid: 'editBillofLadingGrid',
    networkCardGrid: 'networkCardGrid',
    categoryCardGrid: 'categoryCardGrid',
    zReportGrid: 'zReportGrid',
    masterPriceBookWizardGrid: 'masterPriceBookWizardGrid',
    priceGroupMasterAllItemGrid: 'priceGroupMasterAllItemGrid',
    timeOffGetGrid: 'timeOffGetGrid',
    timeOffGetGridByRole: 'timeOffGetGridByRole',
    gridemployeeTimesheetDetail: 'gridemployeeTimesheetDetail',
    adjustemployeeTimesheetDetail: 'adjustemployeeTimesheetDetail',
    invoiceByStoreGrid: 'invoiceByStoreGrid',
    invoiceByUserGrid: 'invoiceByUserGrid',
    masterManufacturerGrid: 'masterManufacturerGrid',
    itemHistoryReportGrid: 'itemHistoryReportGrid',
    itemHistoryByStoreGrid: 'itemHistoryByStoreGrid',
    purchaseHistoryGrid: 'purchaseHistoryGrid',
    purchaseHistoryCartonGrid: 'purchaseHistoryCartonGrid'
};
const defaultSetting = {
    DEFAULT: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        isSearchTextBoxRequired: true,
        rowHeight: 130
    },
    // companyGrid: {
    //     rowSelection: 'single',
    //     pagination: false, // do not use pagination with expandable
    //     paginationPageSize: 15,
    // },
    dataFromPOSGrid: {
        rowSelection: 'single', singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10
    },
    itemListChildGrpGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        headerHeight: 1,
        isSearchTextBoxRequired: true,
        childGridType: gridTypes.itemListChildGrpGridChildGrid,
        detailRowHeight: 250
    },
    itemListOverlayGrpGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        headerHeight: 1,
        paginationPageSize: 10,
        isSearchTextBoxRequired: true,
        childGridType: gridTypes.itemListOverlayGrpGridChildGrid,
        detailRowHeight: 250
    },
    dataToPOSGrid: {
        rowSelection: 'single', singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10
    },

    employeeTimeCardGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10
    },
    itemsInDeptGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10
    },
    lotteryGameGrid: {
        rowSelection: 'multiple',
        pagination: false,
        paginationPageSize: 10,
        suppressRowClickSelection: true
    },
    invoicesDetailsGrid: {
        rowSelection: 'multiple',
        pagination: true,
        paginationPageSize: 10,
        suppressRowClickSelection: true,
        // headerHeight: 30,
        isSuppressMenu: false,
        suppressCellSelection: true,
        rowDeselection: true,
        fullRowEditabeRequired: false,
        singleClickEdit: false,
        rowModelType: 'serverSide',
        rowHeight: 85,
        autoHeight: true,
        enableSorting: true,
        wrapText: true,
        overlayLoadingTemplate: true, // true means we are not showing loading inside grid
    },
    departmentGrid: {
        rowSelection: 'multiple',
        pagination: true,
        paginationPageSize: 10,
        headerHeight: 41,
        suppressRowClickSelection: true
    },
    vendorGrid: {
        rowSelection: 'single',
        pagination: true,
        paginationPageSize: 10,
        headerHeight: 41,
        suppressRowClickSelection: true,
        rowHeight: 250,
        detailRowHeight: 'auto'
    },
    storeInfoGrid: {
        rowSelection: 'single',
        pagination: false,
        paginationPageSize: 10,
        headerHeight: 41,
    },
    fuelGradeMappingGrid: {
        rowSelection: 'single',
        pagination: true,
        paginationPageSize: 10,
    },
    paymentMethodGrid: {
        rowSelection: 'single',
        pagination: true,
        paginationPageSize: 10,
    },
    salesRestrictionGrid: {
        rowSelection: 'single',
        pagination: true,
        paginationPageSize: 10,
        headerHeight: 41,
    },
    salesTaxGrid: {
        rowSelection: 'single',
        pagination: true,
        paginationPageSize: 10,
    },
    storeFeesGrid: {
        rowSelection: 'single',
        pagination: true,
        paginationPageSize: 10,
    },
    paymentSourceGrid: {
        rowHeight: 250,
        rowSelection: 'single',
        pagination: true,
        paginationPageSize: 10,
    },
    masterDepartmentGrid: {
        rowSelection: 'single',
        pagination: false,
        paginationPageSize: 10,
    },
    houseAccountGrid: {
        rowSelection: 'single',
        pagination: true,
        paginationPageSize: 10,
        headerHeight: 50
    },
    departmentLocationGrid: {
        rowSelection: 'single',
        pagination: true,
        paginationPageSize: 10,
        headerHeight: 41
    },
    itemDetailGrid: {
        rowSelection: 'multiple',
        pagination: true,
        paginationPageSize: 25,
        suppressRowClickSelection: true,
        isSideBarRequired: true, /// grid filter sidebar
        //isSuppressMenu: true,
        headerHeight: 41,
        overlayLoadingTemplate: true, // true means we are not showing loading inside grid
        rowModelType: 'serverSide',
        enableSorting: true,
        enableRangeSelection: true,
        wrapText: true,
        rowHeight: 45
    },
    manageItemsGrid: {
        rowSelection: 'multiple',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        headerHeight: 41,
        rowHeight: 45,
        rowModelType: 'serverSide',
        angularCompileRows: true,
        isSuppressMenu: true,
    },
    manageItemsPricingGrid: {
        rowSelection: 'multiple',
        singleClickEdit: false,
        pagination: true,
        paginationPageSize: 10,
        headerHeight: 41,
        rowHeight: 45,
        rowModelType: 'serverSide',
        angularCompileRows: true,
        isSuppressMenu: true,
        fullRowEditabeRequired: false,
        suppressClickEdit: false
    },
    manageItemsPricingGridWithoutStore: {
        rowSelection: 'multiple',
        singleClickEdit: false,
        pagination: true,
        paginationPageSize: 10,
        headerHeight: 41,
        rowHeight: 45,
        rowModelType: 'serverSide',
        angularCompileRows: true,
        isSuppressMenu: true,
        fullRowEditabeRequired: false,
        suppressClickEdit: false
    },
    itemByPriceGroupGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        suppressRowClickSelection: true,
        rowModelType: 'clientSide',
        pagination: true,
        paginationPageSize: 10,
        rowHeight: 36
    },
    manageItemsByPriceGrpGrid: {
        rowSelection: 'multiple',
        singleClickEdit: false,
        pagination: true,
        paginationPageSize: 10,
        rowModelType: 'clientSide',
        rowHeight: 36,
        fullRowEditabeRequired: false,
        suppressClickEdit: false
    },
    manageItemsByPriceGrpGridSingleStore: {
        rowSelection: 'multiple',
        singleClickEdit: false,
        pagination: true,
        paginationPageSize: 10,
        rowModelType: 'clientSide',
        rowHeight: 36,
        fullRowEditabeRequired: false,
        suppressClickEdit: false
    },
    advmultipacksIGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        suppressRowClickSelection: true,
        pagination: false,
        rowModelType: 'clientSide',
        rowHeight: 36
    },
    linkedItemsGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        suppressRowClickSelection: true,
        rowModelType: 'clientSide',
        pagination: false,
        rowHeight: 36
    },
    multiplierItemGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        suppressRowClickSelection: true,
        pagination: false,
        rowModelType: 'clientSide',
        rowHeight: 36
    },
    priceGroupItemGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        suppressRowClickSelection: true,
        rowModelType: 'clientSide',
        pagination: false,
        rowHeight: 36
    },
    storeItemsGrid: {
        rowSelection: 'multiple',
        singleClickEdit: true,
        suppressRowClickSelection: true,
        isSearchTextBoxRequired: false,
        rowModelType: 'clientSide',
        pagination: false,
        groupSelectsChildren: true,
        groupUseEntireRow: true,
        groupDefaultExpanded: -1,
        masterDetail: false,
        groupRowRendererParams: {
            suppressCount: true,
            checkbox: true,
        },
        rowHeight: 36
    },
    editItemVendorGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        suppressRowClickSelection: true,
        rowModelType: 'clientSide',
        pagination: false,
        rowHeight: 36
    },
    storeItemsGridCase: {
        rowSelection: 'single',
        singleClickEdit: true,
        suppressRowClickSelection: true,
        isSearchTextBoxRequired: false,
        rowModelType: 'clientSide',
        pagination: false,
        groupSelectsChildren: true,
        groupUseEntireRow: true,
        groupDefaultExpanded: -1,
        masterDetail: false,
        groupRowRendererParams: {
            suppressCount: true,
            checkbox: true,
            groupSelectsChildren: true,
        },
        rowHeight: 36
    },
    masterDepartmentTypeGrid: {
        rowSelection: 'single',
        pagination: false,
        paginationPageSize: 10,
        headerHeight: 60,
    },
    priceGroupGrid: {
        rowSelection: 'single',
        pagination: false,
        paginationPageSize: 10,
    },
    masterInventoryBuyTagGrid: {
        rowSelection: 'single',
        pagination: true,
        paginationPageSize: 10,
    },
    supreItemsGrid: {
        rowSelection: 'single',
        pagination: true,
        paginationPageSize: 10,
    },
    cBuyDownScheduleGrid: {
        rowSelection: 'single',
        pagination: true,
        paginationPageSize: 10,
        headerHeight: 41,
    },
    addBuyDownScheduleGrid: {
        rowSelection: 'single',
        pagination: true,
        suppressRowClickSelection: true,
        paginationPageSize: 10,
    },
    currentPriceScheduleGrid: {
        rowSelection: 'single',
        pagination: true,
        suppressRowClickSelection: true,
        paginationPageSize: 10,
        headerHeight: 41,
    },
    newPriceScheduleGrid: {
        rowSelection: 'single',
        pagination: true,
        suppressRowClickSelection: true,
        paginationPageSize: 10,
    },
    physicalInventoryGrid: {
        rowSelection: 'single',
        pagination: true,
        suppressRowClickSelection: true,
        paginationPageSize: 10,
        headerHeight: 41,
    },
    activateConfirmGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false
    },
    multipacksIGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        headerHeight: 41,
        isSearchTextBoxRequired: false
    },
    itemRefenceGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        headerHeight: 41,
        isSearchTextBoxRequired: true
    },
    siteMessageGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: true
    },
    userRoleWiseCompanyGrid: {
        rowSelection: 'multiple',
        pagination: false,
        suppressRowClickSelection: true
    },
    // privilageGrid: {
    //     rowSelection: 'single',
    //     pagination: false,
    //     paginationPageSize: 15,
    //     isSearchTextBoxRequired: true
    // },
    fuelGradeTankDetailsGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: true
    },
    storeFuelGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: true
    },
    fuelGradeTankGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 5,
        headerHeight: 41,
        isSearchTextBoxRequired: true
    },
    fuelGradeBlendDetailsGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: true
    },
    // fuelTaxGrid: {
    //     rowSelection: 'single',
    //     singleClickEdit: true,
    //     pagination: true,
    //     paginationPageSize: 10,
    //     isSearchTextBoxRequired: true,
    //     headerHeight: 50,
    // },
    fuelInvoiceGrid: {
        rowSelection: 'multiple',
        pagination: true,
        paginationPageSize: 10,
        suppressRowClickSelection: true,
        // headerHeight: 30,
        isSuppressMenu: false,
        suppressCellSelection: true,
        rowDeselection: true,
        fullRowEditabeRequired: false,
        singleClickEdit: false,
        rowModelType: 'serverSide',
        rowHeight: 85,
        autoHeight: true,
        enableSorting: true,
        wrapText: true,
        overlayLoadingTemplate: true
    },
    binInvoiceGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        suppressRowClickSelection: true,
        isSearchTextBoxRequired: true
    },
    actionInvoiceGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: true
    },
    filesInvoiceGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: true
    },
    orderManagementGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: true
    },
    vendorPaymentGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: true
    },
    reconcileHouseGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false
    },
    validateInvoiceGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: true
    },
    excessInventoryGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        // paginationPageSize: 10,
        isSearchTextBoxRequired: false,
        headerHeight: 55,
    },
    addInvoicesDetailsGrid: {
        rowSelection: 'multiple',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        headerHeight: 55,
        isSearchTextBoxRequired: true,
        suppressRowClickSelection: true

    },
    invoicesDepartmentDetailsGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 5,
        headerHeight: 35,
        isSearchTextBoxRequired: false
    },
    fuelInvoiceDetailGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 5,
        isSearchTextBoxRequired: false
    },
    fuelInvoiceTotalGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 5,
        isSearchTextBoxRequired: false
    },
    pjrSearchGrid: {
        rowSelection: 'single',
        pagination: true,
        paginationPageSize: 20,
        headerHeight: 30,
        isSuppressMenu: true,
        suppressRowClickSelection: false,
        isSearchTextBoxRequired: false,
        suppressCellSelection: true,
        rowDeselection: true,
        fullRowEditabeRequired: false,
        singleClickEdit: false,
        rowModelType: 'serverSide'
    },
    itemUPCDetailGrid: {
        rowSelection: 'multiple',
        pagination: true,
        paginationPageSize: 15,
        headerHeight: 30,
        isSuppressMenu: true,
        suppressRowClickSelection: false,
        isSearchTextBoxRequired: false,
        suppressCellSelection: true,
        rowDeselection: true,
        fullRowEditabeRequired: true,
        singleClickEdit: false,
        rowModelType: 'clientSide'
    },
    companyPriceGroupNewGrid: {
        rowSelection: 'single',
        pagination: true,
        paginationPageSize: 10,
        headerHeight: 35,
        isSuppressMenu: false,
        suppressRowClickSelection: false,
        isSearchTextBoxRequired: false,
        suppressCellSelection: true,
        rowDeselection: true,
        fullRowEditabeRequired: false,
        singleClickEdit: false,
        rowModelType: 'clientSide'
    },
    priceGrpNewItemDetailGrid: {
        pagination: true,
        paginationPageSize: 10,
        headerHeight: 35,
        isSuppressMenu: false,
        suppressRowClickSelection: false,
        isSearchTextBoxRequired: false,
        suppressCellSelection: true,
        rowDeselection: true,
        fullRowEditabeRequired: false,
        singleClickEdit: false,
        rowModelType: 'clientSide',
        rowSelection: 'multiple',
    },
    priceGrpNewItemDetailGrid1: {
        pagination: true,
        paginationPageSize: 10,
        headerHeight: 35,
        isSuppressMenu: false,
        isSearchTextBoxRequired: false,
        suppressCellSelection: true,
        rowDeselection: true,
        fullRowEditabeRequired: false,
        rowModelType: 'clientSide',
        rowSelection: 'single',
        singleClickEdit: true,
        suppressRowClickSelection: true,
        angularCompileRows: true,
        //onRowDoubleClicked: onSelectionChanged
    },
    priceGrpNewItemDetailGrid2: {
        pagination: true,
        paginationPageSize: 10,
        headerHeight: 35,
        isSuppressMenu: false,
        isSearchTextBoxRequired: false,
        suppressCellSelection: true,
        rowDeselection: true,
        fullRowEditabeRequired: false,
        rowModelType: 'clientSide',
        rowSelection: 'multiple',
        singleClickEdit: true,
        suppressRowClickSelection: true,
        angularCompileRows: true,
        //onRowDoubleClicked: onSelectionChanged
    },
    storeMixMatchDetailGrid: {
        pagination: false,
        paginationPageSize: 10,
        headerHeight: 35,
        isSuppressMenu: false,
        isSearchTextBoxRequired: false,
        suppressCellSelection: true,
        rowDeselection: true,
        fullRowEditabeRequired: true,
        rowModelType: 'clientSide',
        rowSelection: 'single',
        singleClickEdit: true,
        suppressRowClickSelection: true,
        angularCompileRows: true,
    },
    storeComboDealDetailGrid: {
        pagination: false,
        paginationPageSize: 10,
        headerHeight: 35,
        isSuppressMenu: false,
        isSearchTextBoxRequired: false,
        suppressCellSelection: true,
        rowDeselection: true,
        fullRowEditabeRequired: true,
        rowModelType: 'clientSide',
        rowSelection: 'single',
        singleClickEdit: true,
        suppressRowClickSelection: true,
        angularCompileRows: true,
    },
    itemMaintanenceGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: true
    },
    itemListMaintanenceGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false
    },
    includedItemListMaintanenceGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false
    },
    stockTransactionsGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: true,
        headerHeight: 50,
    },
    comboMaintanenceGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: true,
        headerHeight: 50
    },
    mixMatchMaintanenceGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: true,
        headerHeight: 50
    },
    companyPriceGroupGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: true,
    },
    tankVolumeHistoryGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: true,
        headerHeight: 50
    },
    competitorPricingGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false,
        headerHeight: 35
    },
    networkSummaryGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false,
        headerHeight: 50,
    },
    fuelReconciliationGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false,
        headerHeight: 50
    },
    fuelReconciliationNetworkBatchGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false,
        headerHeight: 35,
    },
    fuelReconciliationFuelInvoicechGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false,
        headerHeight: 41
    },
    fuelReconciliationOtherChargesGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false,
    },
    storeCompetitorGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: true,
        headerHeight: 35,
    },
    scanDataSetupGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: true,
    },
    billofLadingGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: true,
    },
    taxStrategyGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false,
    },
    salesRestrictCodeGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false,
    },
    tenderCodeGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false,
    },
    mdseCodeGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false,
    },
    passportItemGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false,
    },
    sapphireCustIDGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false,
    },
    sapphireDepartmentGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false,
    },
    sapphireMOPGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false,
    },
    sapphireTaxGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false,
    },
    passportHtmlGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false,
    },
    sapphireItemGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false,
    },
    custIDGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false,
    },
    rubyDepartmentGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false,
    },
    itemFromCSVGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false,
    },
    rubyMOPGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false,
    },
    rubyTaxGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false,
    },
    rubySubashGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false,
    },
    rubyRGISGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false,
    },
    ediInvoiceGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        isSearchTextBoxRequired: false,
    },
    ediProcessGrid: {
        rowSelection: 'multiple',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        isSearchTextBoxRequired: true,
    },
    editfuelReconciliationFuelInvoicechGrid: {
        rowSelection: 'multiple',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 15,
        suppressRowClickSelection: true,
        headerHeight: 50,
        isSearchTextBoxRequired: true,
    },
    editFuelReconciliationNetworkBatchGrid: {
        rowSelection: 'multiple',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 15,
        suppressRowClickSelection: true,
        headerHeight: 50,
        isSearchTextBoxRequired: true,
    },
    MasterPriceBookItemGrid: {
        rowSelection: 'multiple',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        suppressRowClickSelection: true,
        headerHeight: 50,
        isSearchTextBoxRequired: true,
    },
    employeeSetupGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        headerHeight: 50,
        isSearchTextBoxRequired: true,
    },
    importGroupGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        headerHeight: 50,
        isSearchTextBoxRequired: true,
    },
    itemPriceGroupExpandGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        suppressRowClickSelection: true,
        isSearchTextBoxRequired: true
    },
    lotteryInventoryGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        headerHeight: 55,
        // paginationPageSize: 10,
        suppressRowClickSelection: true,
        isSearchTextBoxRequired: true
    },
    repCashCheckAmounGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        suppressRowClickSelection: true,
        isSearchTextBoxRequired: true
    },
    repDepartmentTypeSalesGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        suppressRowClickSelection: true,
        isSearchTextBoxRequired: true
    },
    repGasGradeDatasGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        suppressRowClickSelection: true,
        isSearchTextBoxRequired: true
    },
    repMOPDetailsGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        suppressRowClickSelection: true,
        isSearchTextBoxRequired: true
    },
    zReportGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        suppressRowClickSelection: true,
        isSearchTextBoxRequired: true
    },
    storeHealthGrid: {
        rowSelection: 'single',
        pagination: false,
        headerHeight: 45,
        suppressRowClickSelection: true,
    },
    serviceHealthGrid: {
        rowSelection: 'single',
        pagination: false,
        headerHeight: 45,
        suppressRowClickSelection: true,
    },
    pjrGrid: {
        rowSelection: 'single',
        pagination: false,
        headerHeight: 45,
        suppressRowClickSelection: true,
    },
    dayReconGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        headerHeight: 45,
        paginationPageSize: 10,
        suppressRowClickSelection: true,
        isSearchTextBoxRequired: true
    }, dashboardGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        suppressRowClickSelection: true,
        isSearchTextBoxRequired: true
    }, subscriptionDetailGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        suppressRowClickSelection: true,
        isSearchTextBoxRequired: false
    },
    storeBillingSubPaymentHistoryGridCol: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        suppressRowClickSelection: true,
        isSearchTextBoxRequired: false
    },
    storeBillingSubSubscriptionHistoryGridCol: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        suppressRowClickSelection: true,
        isSearchTextBoxRequired: false
    }, expensesGrid: {
        rowSelection: 'single',
        // singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        // suppressRowClickSelection: true
        // suppressRowClickSelection: true,
        // isSearchTextBoxRequired: false
    },
    dayReconGasDetailGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        headerHeight: 70,
        pagination: false,
        paginationPageSize: 10,
        suppressRowClickSelection: true,
        isSearchTextBoxRequired: false
    },
    networkCardGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        suppressRowClickSelection: true,
        isSearchTextBoxRequired: false
    },
    categoryCardGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: false,
        paginationPageSize: 10,
        suppressRowClickSelection: true,
        isSearchTextBoxRequired: false
    },
    purchasesGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        headerHeight: 1,
        pagination: false,
        paginationPageSize: 10,
        suppressRowClickSelection: true,
        isSearchTextBoxRequired: false
    },
    importPurchasesGrid: {
        rowSelection: 'multiple',
        singleClickEdit: true,
        headerHeight: 35,
        pagination: false,
        paginationPageSize: 10,
        suppressRowClickSelection: true,
        isSearchTextBoxRequired: false
    },
    importFuelPurchasesGrid: {
        rowSelection: 'multiple',
        singleClickEdit: true,
        headerHeight: 35,
        pagination: false,
        paginationPageSize: 10,
        suppressRowClickSelection: true,
        isSearchTextBoxRequired: false
    },
    dayReconPromotionsDetailGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        headerHeight: 70,
        pagination: true,
        paginationPageSize: 10,
        suppressRowClickSelection: true,
        enableRangeSelection: true,
        isSearchTextBoxRequired: false
    },
    expensesDetailGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        headerHeight: 40,
        pagination: true,
        paginationPageSize: 10,
        suppressRowClickSelection: true,
        isSearchTextBoxRequired: false
    },
    masterPriceGropDetailGrid: {
        rowHeight: 250,
        rowSelection: 'single',
        singleClickEdit: true,
        headerHeight: 40,
        pagination: false,
        paginationPageSize: 10,
        suppressRowClickSelection: true,
        isSearchTextBoxRequired: false
    },
    salesTotalMgmtGrid: {
        rowSelection: 'single',
        // singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
    },
    priceGrpItemDetailGrid: {
        rowSelection: 'multiple',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 5,
        //  paginationAutoPageSize: 11,
        isSearchTextBoxRequired: true,
    },
    companyPriceGroupChildGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 20,
        isSearchTextBoxRequired: true,
    },

    storeGrpGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: true,
    },
    scanDataConfig: {
        rowSelection: 'single',
        pagination: false,
        paginationPageSize: 10,
        headerHeight: 35,
        isSuppressMenu: false,
        suppressRowClickSelection: false,
        isSearchTextBoxRequired: false,
        suppressCellSelection: true,
        rowDeselection: true,
        fullRowEditabeRequired: false,
        singleClickEdit: false,
        rowModelType: 'clientSide',
        enableSorting: true
    },
    scanDataAcknowledgment: {
        rowSelection: 'single',
        pagination: false,
        paginationPageSize: 10,
        headerHeight: 35,
        isSuppressMenu: false,
        suppressRowClickSelection: false,
        isSearchTextBoxRequired: false,
        suppressCellSelection: true,
        rowDeselection: true,
        fullRowEditabeRequired: false,
        singleClickEdit: false,
        rowModelType: 'clientSide',
        enableSorting: true
    },
    invoiceDashboardGrid: {
        rowSelection: 'single',
        pagination: false,
        paginationPageSize: 10,
        // headerHeight: 35,
        isSuppressMenu: false,
        suppressRowClickSelection: false,
        isSearchTextBoxRequired: false,
        suppressCellSelection: true,
        rowDeselection: true,
        fullRowEditabeRequired: false,
        singleClickEdit: false,
        rowModelType: 'clientSide',
        enableSorting: true
    },
    ismUpdate: {
        rowSelection: 'multiple',
        pagination: true,
        paginationPageSize: 100,
        headerHeight: 35,
        isSuppressMenu: false,
        suppressRowClickSelection: false,
        isSearchTextBoxRequired: false,
        suppressCellSelection: true,
        rowDeselection: true,
        fullRowEditabeRequired: false,
        singleClickEdit: false,
        rowModelType: 'clientSide',
        enableSorting: true
    },
    itemCatalogGrid: {
        rowSelection: 'multiple',
    },
    timeOffGetGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: true,
    },
    itemCatalogStoreGrid: {
        rowSelection: 'multiple',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 12,
        isSearchTextBoxRequired: true,
    },
    buyDownGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10
    },
    buyDownStoreDetailsGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10
    },
    priceGroupBuyDownGrid: {
        rowSelection: 'single',
        // singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10
    },
    editBillofLadingGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        suppressRowClickSelection: true,
        headerHeight: 35,
        pagination: true,
        paginationPageSize: 10
    },
    itemHistoryReportGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        suppressRowClickSelection: true,
        headerHeight: 35,
        pagination: false,
        paginationPageSize: 10,
        enableSorting: true
    },
    itemHistoryByStoreGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        suppressRowClickSelection: true,
        headerHeight: 35,
        pagination: false,
        paginationPageSize: 10,
        enableSorting: true
    },
    purchaseHistoryGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        suppressRowClickSelection: true,
        headerHeight: 35,
        pagination: false,
        paginationPageSize: 10,
        enableSorting: true
    },
    purchaseHistoryCartonGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        suppressRowClickSelection: true,
        headerHeight: 35,
        pagination: false,
        paginationPageSize: 10,
        enableSorting: true
    },
    fuelTaxGrid: {
        rowSelection: 'single',
        singleClickEdit: false,
        suppressRowClickSelection: true,
        isSearchTextBoxRequired: false,
        suppressCellSelection: true,
        rowDeselection: true,
        fullRowEditabeRequired: true,
    },
    fuelInventoryActivityGrid: {
        rowSelection: 'single',
        pagination: false,
        paginationPageSize: 10,
        // headerHeight: 35,
        isSuppressMenu: false,
        suppressRowClickSelection: false,
        isSearchTextBoxRequired: false,
        suppressCellSelection: true,
        rowDeselection: true,
        fullRowEditabeRequired: false,
        singleClickEdit: false,
        rowModelType: 'clientSide',
        enableSorting: true
    },
    masterPriceBookWizardGrid: {
        rowSelection: 'multiple',
        singleClickEdit: false,
        suppressRowClickSelection: true,
        isSearchTextBoxRequired: false,
        suppressCellSelection: true,
        rowDeselection: true,
        fullRowEditabeRequired: false,

        pagination: false,
        headerHeight: 35,
        isSuppressMenu: false,
        rowModelType: 'clientSide',
        enableSorting: true
    },


    priceGroupMasterAllItemGrid: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: true,
    },

    timeOffGetGridByRole: {
        rowSelection: 'single',
        singleClickEdit: true,
        pagination: true,
        paginationPageSize: 10,
        isSearchTextBoxRequired: true,
    },
    invoiceByStoreGrid: {
        rowSelection: 'single',
        pagination: true,
        paginationPageSize: 10,
        headerHeight: 35,
        isSuppressMenu: false,
        suppressRowClickSelection: false,
        isSearchTextBoxRequired: false,
        suppressCellSelection: true,
        rowDeselection: true,
        fullRowEditabeRequired: false,
        singleClickEdit: false,
        rowModelType: 'clientSide'
    },
    invoiceByUserGrid: {
        rowSelection: 'single',
        pagination: true,
        paginationPageSize: 10,
        headerHeight: 35,
        isSuppressMenu: false,
        suppressRowClickSelection: false,
        isSearchTextBoxRequired: false,
        suppressCellSelection: true,
        rowDeselection: true,
        fullRowEditabeRequired: false,
        singleClickEdit: false,
        rowModelType: 'clientSide'
    },
    masterManufacturerGrid: {
        rowSelection: 'single',
        pagination: false,
        isSuppressMenu: false,
        suppressRowClickSelection: false,
        isSearchTextBoxRequired: true,
        suppressCellSelection: true,
        rowDeselection: true,
        fullRowEditabeRequired: false,
        singleClickEdit: false,
        rowModelType: 'clientSide',
        enableSorting: true
    },
    masterBrandGrid: {
        rowSelection: 'single',
        pagination: false,
        isSuppressMenu: false,
        suppressRowClickSelection: false,
        isSearchTextBoxRequired: true,
        suppressCellSelection: true,
        rowDeselection: true,
        fullRowEditabeRequired: false,
        singleClickEdit: false,
        rowModelType: 'clientSide',
        enableSorting: true
    },
};

export const gridOptions = {
    gridTypes: gridTypes,
    defaultSetting: defaultSetting
};
