export const reportTypes = {
    PurchaseReportsByWeeklys: 'PurchaseReportsByWeeklys',
    PurchaseByInvoiceStatusReport: 'PurchaseByInvoiceStatusReport',
    PurchaseByInvoiceStatusReportDetails: 'PurchaseByInvoiceStatusReportDetails',
    weeklyPurchaseReport: 'weeklyPurchaseReport',
    weeklySaleByDepartmentTypeReport: 'weeklySaleByDepartmentTypeReport',
    purchaseReportByItem: 'purchaseReportByItem',
    purchaseReportByDepartment: 'purchaseReportByDepartment',
    fuelSalesReport: 'fuelSalesReport',
    purchaseReportByItemDetail: 'purchaseReportByItemDetail',
    purchaseReport: 'purchaseReport',
    purchaseReportByVendor: 'purchaseReportByVendor',
    departmentSalesReportDetail: 'departmentSalesReportDetail',
    itemSalesReport: 'itemSalesReport',
    itemSalesReportDetail: 'itemSalesReportDetail',
    salesPercentReport: 'salesPercentReport',
    promotionItemsReport: 'promotionItemsReport',
    salesReportByVendor: 'salesReportByVendor',
    salesReport: 'salesReport',
    salesReportByPriceGroup: 'salesReportByPriceGroup',
    departmentSalesReport: 'departmentSalesReport',
    SalesComparisonReport: 'SalesComparisonReport',
    taxableItemsReport: 'taxableItemsReport',
    salesComparisionYearAgoReport: 'salesComparisionYearAgoReport',
    abnormalProfitMarginReport: 'abnormalProfitMarginReport',
    salesHistoryByUPCReport: 'salesHistoryByUPCReport',
    modifierSalesReport: 'modifierSalesReport',
    sirInventoryControlReport: 'sirInventoryControlReport',
    inventoryReport:'InventoryReport',
    lotteryInventoryReport:'lotteryInventoryReport',
    itemTxnReport:'itemTxnReport',
    shrinkageReport:'shrinkageReport',
    unupdatedInventoryReport:'unupdatedInventoryReport',
    inventoryPurchaseReport: 'inventoryPurchaseReport',
    inventoryPurchaseDetailReport: 'inventoryPurchaseDetailReport',
};
